# This workflow will build a Java project with Maven and then deploys it to Heroku using Docker
# For more information see:
#  - https://github.com/marketplace/actions/deploy-docker-image-to-heroku-app

name: CI with NPM and CD with Heroku and Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '12.x'
      - name: Test with NPM
        run: |
          npm install
          npm run lint
          npm run build -- --prod
      - name: Build Docker image and deploy to Heroku
        if: ${{ github.event_name == 'push' }}
        uses: jctaveras/heroku-deploy@v2.1.1
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          api_key: ${{ secrets.HEROKU_API_KEY }}
          app_name: 'agridata-hub'
          dockerfile_path: ''
